### ISSUE TITLE
王同学您好，关于论文的一些问题希望得到您的解答。

### ISSUE THREAD

**Issue by xiaolongren777** [wangxiaohit/GNNPN-SC#2]
王同学你好，有幸读完您的论文，您的方法对我启发很大，希望能将部分方法应用于我的研究当中，现在有一些关于代码和数据库的问题，希望得到您的解答，万分感谢。希望能够留下你的联系方法，微信，qq或者邮箱，希望得到您的回复，谢谢。

**Comment by wangxiaohit** [comment]
Replies have been made by email

**Comment by wangxiaohit** [comment]
Replies have been made by email
